apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-web-helm
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/maortaieb/k8s-web-helm
    targetRevision: main
    path: helm/k8s-web-helm
    helm:
      releaseName: k8s-web-helm
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: test2

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

